Rename Name to Players in HomeController.Index and more changes
yuriyoleynikov/YoTennis pull request #16
Opened 2017-05-18 09:02 UTC by yuriyoleynikov

2017-05-18 15:43 UTC, Igorbek requested changes

2017-05-18 15:43 UTC, Igorbek commented on src/YoTennis/Controllers/HomeController.cs
> +                string score = "";
- [ ] Create a separate function
- [ ] use `StringBuilder` instead of `string`. google how to use it, if you don't know

2017-05-19 14:41 UTC, yuriyoleynikov commented on src/YoTennis/Controllers/HomeController.cs
> +                string score = "";
Done

2017-05-19 14:57 UTC, Igorbek approved these changes

2017-05-19 14:58 UTC, merged