Implement GameModel class.
yuriyoleynikov/YoTennis pull request #2
Opened 2016-12-01 14:23 UTC by yuriyoleynikov

Addresses #1

2016-12-01 16:42 UTC, Igorbek requested changes

2016-12-01 16:42 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +        public bool FirstPlayerAction { get; set; }
why do you need two flags here: one who gets point and other who made action. doesn't point kind show that the same player gets point or not?

2016-12-01 16:42 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +    public struct Score
is that current score? isn't that part of the state?

2016-12-01 16:42 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +
TBD, I guess?

2016-12-01 17:17 UTC, Igorbek commented
```cs
class GameHandler
{
  // any state data
  
  public void AddEvent(GameEvent e)
  {
    ((dynamic)this).On((dynamic)e);
  }

  private void On(DrawEvent e)
  {
     ...
  }

  private void On(ServeFailEvent e)
  {
    ...
  }
}
```

2016-12-21 06:22 UTC, Igorbek requested changes

2016-12-21 06:22 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +        public void AddPoint(Player getPointPlayer)
should be private

2016-12-21 06:22 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +            if (score.FirstPlayer >= 4 && score.SecondPlayer + 1 < score.FirstPlayer)
minor optimization: since you already know who's got a point, than you can test only for that player.

2016-12-21 06:22 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +            if (currentSetScore.FirstPlayer >= 6 && currentSetScore.SecondPlayer + 1 < currentSetScore.FirstPlayer)
same optimization could be performed

2016-12-21 06:22 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +            if (currentSetScore.FirstPlayer >= 6 && currentSetScore.SecondPlayer + 1 < currentSetScore.FirstPlayer)
even if it's well-known constant prescribed in the game rules, I'd suggest to move '6' into a constant. Define a class like `public static class TennisConstants { ... public const int GamesInSet = 6; ... }`

2016-12-21 06:22 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +                CurrentState.ChangeSides = true;
what does this `ChangeSides` field mean? You already have such state, don't you?

2016-12-21 06:22 UTC, Igorbek commented on src/YoTennis/Models/StateData.cs
>          Comleted
typo: `Completed`

2016-12-21 06:22 UTC, Igorbek commented on tests/YoTennis.Tests/Test/YoTennisTest.cs
> +            myGame.CurrentState.MatchSettings.TieBreakFinal.Should().Be(false);
you already have this tested, right? do not duplicate, just test for new state.

2016-12-21 14:00 UTC, yuriyoleynikov commented on src/YoTennis/Models/GameModel.cs
> +        public void AddPoint(Player getPointPlayer)
ok

2016-12-21 14:00 UTC, yuriyoleynikov commented on src/YoTennis/Models/GameModel.cs
> +            if (score.FirstPlayer >= 4 && score.SecondPlayer + 1 < score.FirstPlayer)
ok

2016-12-21 14:00 UTC, yuriyoleynikov commented on src/YoTennis/Models/GameModel.cs
> +            if (currentSetScore.FirstPlayer >= 6 && currentSetScore.SecondPlayer + 1 < currentSetScore.FirstPlayer)
ok

2016-12-21 14:01 UTC, yuriyoleynikov commented on src/YoTennis/Models/GameModel.cs
> +            if (currentSetScore.FirstPlayer >= 6 && currentSetScore.SecondPlayer + 1 < currentSetScore.FirstPlayer)
ok

2016-12-21 14:01 UTC, yuriyoleynikov commented on src/YoTennis/Models/GameModel.cs
> +                CurrentState.ChangeSides = true;
for feature

2016-12-21 14:01 UTC, yuriyoleynikov commented on src/YoTennis/Models/StateData.cs
>          Comleted
ok)

2016-12-21 14:01 UTC, yuriyoleynikov commented on tests/YoTennis.Tests/Test/YoTennisTest.cs
> +            myGame.CurrentState.MatchSettings.TieBreakFinal.Should().Be(false);
ok

2016-12-28 21:26 UTC, Igorbek requested changes

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/Events/ChangeSidesOnTiebreakGame.cs
> +    public class ChangeSidesOnTiebreakGame : GameEvent
`ChangeSidesOnTiebreakEvent`

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/Events/GameEvent.cs
> +        public DateTime OccuredAt;
`{ get; set; }` - all other events have properties

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +            if (CurrentState.MatchState == MatchState.PlayingGame)
what if state is neither `PlayingGame` nor `PlayingTiebreak`?

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/GameModel.cs
> +                        ServePositionOnTheCenterLine.Right : ServePositionOnTheCenterLine.Left;
You can create other extension method `Other` for `ServePositionOnTheCenterLine`.

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/Events/StartTieBreakEvent.cs
> +    public class StartTieBreakEvent : GameEvent
inconsistency: sometime you write `TieBreak` as it were two words 'tie break', sometimes you use `Tiebreak` as it were a single word 'tiebreak'. Clarify and align.

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/MatchSettings.cs
> +        public bool TieBreakFinal { get; set; }
these will be `0` by default. Do you verify that they are set somewhere?

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/PlayerExtentions.cs
> +    public static class PlayerExtentions
You can just call it `Extensions` and use for `Player`, `PlayerScore` and other extensions.

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/PlayerScore.cs
> +    public struct PlayerScore
I'd suggest to call it just `Score` since it holds scores for both players. Current name is not precise.

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public PlayerScore ScoreOnSets { get; set; }
name: `SetScore`

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public List<Set> ScoreInSets { get; set; }
name: `Sets`

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public DateTime GameTime { get; set; }
name: `GameStartedAt`

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public ServePositionOnTheCenterLine ServePositionOnTheCenterLine { get; set; }
name: `ServePosition` ?

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public DateTime MatchDate { get; set; }
name: `MatchStartedAt`

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public MatchState MatchState { get; set; }
name: `State`

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public ServeSpeed ServeSpeed { get; set; }
what is the purpose for that?

2016-12-28 21:26 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        BeginTieBreak,
`BeginningTieBreak` ?

2016-12-29 12:09 UTC, yuriyoleynikov commented on src/YoTennis/Models/Events/ChangeSidesOnTiebreakGame.cs
> +    public class ChangeSidesOnTiebreakGame : GameEvent
ok

2016-12-29 12:10 UTC, yuriyoleynikov commented on src/YoTennis/Models/Events/GameEvent.cs
> +        public DateTime OccuredAt;
ok

2016-12-29 12:19 UTC, yuriyoleynikov commented on src/YoTennis/Models/GameModel.cs
> +            if (CurrentState.MatchState == MatchState.PlayingGame)
ok. Exception?

2016-12-29 12:22 UTC, yuriyoleynikov commented on src/YoTennis/Models/GameModel.cs
> +                        ServePositionOnTheCenterLine.Right : ServePositionOnTheCenterLine.Left;
ok

2016-12-29 12:35 UTC, yuriyoleynikov commented on src/YoTennis/Models/Events/StartTieBreakEvent.cs
> +    public class StartTieBreakEvent : GameEvent
ok

2016-12-29 12:37 UTC, yuriyoleynikov commented on src/YoTennis/Models/MatchSettings.cs
> +        public bool TieBreakFinal { get; set; }
ok. But thi set in the StartGameEvent

2016-12-29 12:38 UTC, yuriyoleynikov commented on src/YoTennis/Models/PlayerExtentions.cs
> +    public static class PlayerExtentions
ok

2016-12-29 12:39 UTC, yuriyoleynikov commented on src/YoTennis/Models/PlayerScore.cs
> +    public struct PlayerScore
ok

2016-12-29 12:41 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public PlayerScore ScoreOnSets { get; set; }
ok

2016-12-29 12:41 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public List<Set> ScoreInSets { get; set; }
ok

2016-12-29 12:43 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public DateTime GameTime { get; set; }
ok

2016-12-29 12:45 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public ServePositionOnTheCenterLine ServePositionOnTheCenterLine { get; set; }
yes

2016-12-29 12:45 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public DateTime MatchDate { get; set; }
ok

2016-12-29 12:46 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public MatchState MatchState { get; set; }
class name is State

2016-12-29 12:47 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public ServeSpeed ServeSpeed { get; set; }
Ball feed rate

2016-12-29 12:48 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        BeginTieBreak,
ok

2016-12-29 17:42 UTC, Igorbek requested changes

2016-12-29 17:42 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public Game GameScore { get; set; }
`GameScore` is not a `Score`. It's a `Game`. So, why did you call it `*Score`? I suggest to call it just `Game`.

2016-12-29 17:42 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        BeginTiebreak,
**`Beginning`**`Game`, but **`Begin`**`Tiebreak`

2016-12-29 17:45 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +        public ServeSpeed ServeSpeed { get; set; }
Why it's here in the state? Because service speed is on every serve, but this one is in the state. So is it last or average?

2016-12-30 09:12 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        BeginTiebreak,
ok

2016-12-30 09:14 UTC, yuriyoleynikov commented on src/YoTennis/Models/State.cs
> +        public Game GameScore { get; set; }
ok

2017-01-04 13:30 UTC, merged

2017-01-04 16:13 UTC, Igorbek commented on src/YoTennis/Models/State.cs
> +    }
Ok, I meant you would rename `BeginTiebreak` to `BeginningTiebreak`.
Now you still have inconsistency:
_verb + object_: `BeginGame`, `BeginTiebreak`
_gerund [+ object]_: `Drawing`, `PlayingGame`, `ChangingSides`, `PlayingTiebreak`, `ChangingSidesOnTiebreak`
_adjective_: `Completed`
_adjective phrase_: `NotStarted`

From the language perspective, both _gerunds_ and _adjectives_ are _adjective phrases_. So only form with a _verb_ is inconsistent. Note the proper spelling: _Begi**nn**ing_.