Player to userid
yuriyoleynikov/YoTennis pull request #32
Opened 2017-08-23 14:25 UTC by yuriyoleynikov

2017-08-24 02:44 UTC, Igorbek requested changes

2017-08-24 02:44 UTC, Igorbek commented on src/YoTennis/Controllers/MatchController.cs
> +                e.FirstPlayerUserId = "none";
use `null`

2017-08-24 02:44 UTC, Igorbek commented on src/YoTennis/Models/MatchDetailsViewModel.cs
> +        public string UserId { get; set; }
do not expose user id, just use user name

2017-08-24 02:44 UTC, Igorbek commented on src/YoTennis/Services/DatabaseMatchService.cs
> +        public async Task PlayerToUserAsync(Player player)
what does this method do?

2017-08-24 02:45 UTC, Igorbek commented on tests/YoTennis.Tests/Test/HandlerSnapshotTests.cs
> +    {/*
why did you comment the tests?

2017-10-04 04:15 UTC, Igorbek commented
Are you going to complete/merge this?

2017-10-13 15:33 UTC, yuriyoleynikov commented on src/YoTennis/Controllers/MatchController.cs
> +                e.FirstPlayerUserId = "none";
ok

2017-11-21 00:42 UTC, Igorbek approved these changes

2017-11-21 00:43 UTC, merged